### PR TITLE
added travis ci

### LINKED ISSUE #41: Add testing framework and continious integration
Travis CI is free for open source projects and integrates well with GitHub.

### PR DESCRIPTION
**Pull request by illing2005**
fixes #41

### CODE REVIEW

**Comment by dahoo** [comment]
Works! :+1:

**Comment by hrantzsch** [comment]
Is the mysql requirement commented because we actually don't need it or is it for your local config?

**Comment by illing2005** [comment]
We don't need it. 
Locally we use SQLite and on heroku Postgres

**Comment by hrantzsch** [comment]
Good, I thought so. We can take it out entirely then :)
Oh, but I think python3 won't work, will it?

**Pull request merged**
