### PR TITLE
Add API route for locations, don't inline locations

### PR DESCRIPTION
**Pull request by dahoo**

### CODE REVIEW

**Comment by dahoo** [comment]
@refugeehackathon/interpreteer Any comments?

**Comment by Bartzi** [comment]
:+1: did not see that this is a PR ;) thought it is an issue^^

**Comment by illing2005** [comment]
Did not test it, but I think the `create` methods have to be adjusted. 
Also I am not sure, why you don't like the inline?

**Comment by Bartzi** [comment]
the inline does not really work with ember.js :/

**Comment by Bartzi** [comment]
@illing2005 you are right, the following `create` methods need to be updated:
- https://github.com/refugeehackathon/interpreteer-backend/blob/master/bill_board/serializers.py#L35
- https://github.com/refugeehackathon/interpreteer-backend/blob/master/bill_board/serializers.py#L56

**Comment by dahoo** [comment]
Done. I also split the location string field in two float fields.

**Comment by dahoo** [comment]
Sure, you're right. Removed.

**Comment by illing2005** [comment]
:+1:

**Pull request merged**
